### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by DaveQB** [BTCMarkets/API#1]
Or am I just not calling it correctly?

**Comment by Hasimir** [comment]
It depends on what you mean by "work".  The ticker is fine, but anything with authentication is anyone's guess at this point.

**Comment by JarrodCrane** [comment]
Hi Dave,

Yes the api is working. If you are having problems connecting feel free to post specific details of the problem here or email support@btcmarkets.net. We are looking at updating the documentation and sample code to include more languages soon. Authentication can be tricky to get right and we are looking at making this easier to troubleshoot.
