### ISSUE TITLE
When i trying to obtain data from public endpoints there are always 403 Forbidden 

### ISSUE THREAD

**Issue by PavloRiyskii** [BTCMarkets/API#131]
When i trying to obtain data from endpoints like https://api.btcmarkets.net/market/ETH/AUD/orderbook its always return response with recaptcha.

**Comment by justin-ngin** [comment]
Hi @PavloRiyskii , 

This will require some personal information exchanged. Could you please open a [support ticket](https://btcmarkets.net/support) with the type of API support so that we can communicate directly?

Regards,
Justin

**Comment by mshvern** [comment]
I have the same issue.
This simple code should give a .json table, but instead it's a horrible html mess with recaptcha

```
source_endpoint_url = 'https://api.btcmarkets.net/market/BTC/AUD/tick.json'

    headers = {
        'Content-type': 'application/json',
        'User-Agent': "Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/532.9 (KHTML, like Gecko) Chrome/5.0.307.11 Safari/532.9"
    }
    r = requests.get(source_endpoint_url, headers=headers, verify=True)
    print(r.text)
```

**Comment by martin-nginio** [comment]
Hi @PavloRiyskii and @mshvern 

Thank you for your feedback. 

We have been able to track those issues with CloudFlare for our other API customers, and in those cases, CloudFlare provides you with an HTML response (instead of a normal API json response ) when they determine that the request is invalid (e.g., suspected for SQL injection) 

If you are still experiencing with issues, please contact our support team via our website and we should be able to assist you (we'd need to get some private information from you including your IP address) 

Thanks and I'm closing this issue for now. 

Regards,
Martin
