### ISSUE TITLE
WebSocket v2 - add currency, amount and fee to fundChange

### ISSUE THREAD

**Issue by WudsyWudsyWudsy** [BTCMarkets/API#158]
Feedback regarding the new WebSocket v2 Beta.

The current `Deposit` information under `fundChange` does not provide much useful information. `Withdrawal` is untested but I assume the same.

**Current fundChange**
 ``` javascript
{ fundtransferId: 3174422768,
  type: 'Deposit',
  status: 'Complete',
  timestamp: '2019-04-13T01:38:02.931Z',
  messageType: 'fundChange' }
```

Providing the `fundtransferId` does allow the user to use the API to get the remaining information, however it would be much easier if the `fundChange` message also included the `currency`, `amount` and `fee` of the deposit / withdrawal.

Can also include `description`, `creationTime`, `errorMessage`, `lastUpdate` and `cryptoPaymentDetail` for completeness, however not super important for me.

**Comment by martin-nginio** [comment]
Let me discuss this further with the team and I will get back to you. The initial idea was to leave this for users to make REST API call in order to get more detail including the ones you mentioned and also more specific information like blockchain transaction id, and fiat banking detail,  etc). Given the amount of data to represent a withdraw or deposit, we might leave this as as a basic notification event only for fund transfers so users can retrieve more info via REST api call.

Hope this makes helps. 

Thanks for your feedback.

**Comment by WudsyWudsyWudsy** [comment]
I don't foresee a case when one would subscribe to `fundChange` and not want to know the `currency`, `amount` and `fee` of their deposits and withdrawals. Hence I believe following a `fundChange` message, 100% of the time the user would be required to create a REST API call. The rest of the data may or may not be relevant, hence I can understand cutting that.

This is very easy to implement so its not a big issue if it is kept the same, I just see no point in there being two steps.

**Comment by martin-nginio** [comment]
`currency`,  `amount` and `fee` attributes now are part of the `fundChange` message. 

Thanks for the feedback.

**Comment by WudsyWudsyWudsy** [comment]
Awesome!
