### ISSUE TITLE
API v3 InvalidAuthSignature on accounts/me/transactions path

### ISSUE THREAD

**Issue by jbcl-io** [BTCMarkets/API#176]
I'm getting `{ code: 'InvalidAuthSignature', message: 'invalid signature' }` response when `GET`-ing `https://api.btcmarkets.net/v3/accounts/me/transactions?assetName=BTC&limit=10`.

Keys are correct and signature is also signed correctly. I can call other paths such as 

`https://api.btcmarkets.net/v3/markets` and
`https://api.btcmarkets.net/v3/markets/tickers?marketId=BTC-AUD`.

Both of those return success.

What am I doing wrong here? Maybe it has something to do with pagination?

**Comment by jbcl-io** [comment]
Looks like calling anything under `accounts/me/*` responds with the error.

**Comment by martin-nginio** [comment]
Hi @jeffbocala 

Thanks for your feedback.
 
This is **probably** due to how string to sign is created when building the authentication signature.  please note the string to sign is ` "GET" +  path + timestamp` and the `path` here does not include query string.  

Alternatively, we have sample authentication code in few  programming languages here:
https://github.com/BTCMarkets

Also, feel free to share code snippet (only parts of the code that can be shared publicly) and we will try to help. 

Thanks.

Regards,
Martin

**Comment by martin-nginio** [comment]
I assume you can call other private APIs fine (e.g. `v3/markets` is a public and does not need authentication)

**Comment by jbcl-io** [comment]
@martin-nginio — ah yes that would be because of the `path` part of the message string not being correct. Thank you for your help 👍
