### ISSUE TITLE
currency pairs

### ISSUE THREAD

**Issue by jumpinjoey222** [BTCMarkets/API#30]
Does the API support bids and asks between currency pairs? Looks like it only supports AUD as a currency.

**Comment by martin-nginio** [comment]
Hi @jumpinjoey222 

Similar to BTC Markets website, you should be able to use the API in order to trade currency pairs (all request/response are the same). 

Below is tick for buying ETH using BTC. 
https://api.btcmarkets.net/market/ETH/BTC/tick 

Hope this answers your question.

Thanks. 

Regards,
Martin

**Comment by jumpinjoey222** [comment]
Thank you Martin
