### ISSUE TITLE
Unexpected results from /order/trade/history endpoint

### ISSUE THREAD

**Issue by s8m7p** [BTCMarkets/API#34]
I'm getting unexpected results when comparing the API results with the following ETH/AUD trades from my account Trade History on the website.

Trade IDs:
> 533884871 <-- oldest
> 541239695
> 630427950
> 638544890
> 656555233
> 661178288 <-- newest

I want to be able to query _x_ number of trades made after a specified trade ID.
For example, the request I've used to get my 2 oldest trades is:
`{ currency: 'AUD', instrument: 'ETH', limit: 2, since: 533884871 }` <-- oldest trade ID

I'm expecting this to return the trades with IDs:
> 533884871 <-- oldest
> 541239695

However it returns the 2 newest trades instead:
> 661178288 <-- newest
> 656555233

Is the trade ID I'm passing in as the 'since' parameter the correct ID? I noticed in the sample request [here ](https://github.com/BTCMarkets/API/wiki/Trading-API#trade-history) the length of the trade ID is 11 digits, whereas the trade ID I'm passing in is only 9 digits long.

**Comment by martin-nginio** [comment]
Hi @s8m7p 

Thank you for sharing a clear description of the issue you are experiencing with pagination of the trade history API.

The current API always returns newest records which only allows for paging backward and it may not be suitable for all situations. 

Our engineering team is the process of introducing an improved history API which allows for both backward and forward pagination allowing you to control direction for your pagination. The new API is also more flexible so yo do not have to pass `since` parameter if you are only after most recent records.  This is expected to be available very soon. 

In the meantime, please feel free to take a look at Fund transfer history API which offers the new pagination method and please let us know if you have any feedback:
https://github.com/BTCMarkets/API/wiki/Fund-Transfer-API  (scroll down to the history section)

Thanks.

Regards,
Martin

**Comment by s8m7p** [comment]
Hi Martin,

Thanks for the quick response. I've tested both the backward and forward pagination of the fund transfer history API. This will work exactly as needed when it is available for the trade history etc.

Will this be made available as a separate API version or will these changes break any code using the current version of the API?

Thanks,
Scott.

**Comment by martin-nginio** [comment]
Thank you for checking this out. 

Our engineering team has confirmed that the new pagination method will be made available to other APIs (at this stage for order/trade history APIs) in the near future and in the same API version (the current order/trade history API are using POST method and the new APIs will be in GET). 

Regards,
Martin
