### ISSUE TITLE
What are the correct units for creating an API order for ETH in AUD?

### ISSUE THREAD

**Issue by simonmittag** [BTCMarkets/API#35]
Hi,

i'm writing an api order client. What units are ETH orders specified in? is it Wei?

Background:

`try {
			// input parameters for creating a new account. data is posted via https
			String postData = "{\"currency\":\"AUD\",\"instrument\":\"BTC\",\"price\":13000000000,\"volume\":10000000,\"orderSide\":\"Bid\",\"ordertype\":\"Limit\",\"clientRequestId\":\"1\"}";
`
In the bitcoin example here, the price and volume have high values, probably 'satoshi' or multiples of 0.00000001 btc:

13000000000 * 0.00000001 = 130 AUD
10000000 * 0.00000001 = 0.1 BTC

For ETH, units are normally Wei (1.000.000.000.000.000.000 wei = 1 ETH), does this mean I need to multiply both AUD price and volume fields with 1.000.000.000.000.000.000?

Thanks,

Simon

**Comment by martin-nginio** [comment]
Hi @simonmittag 

Currently API takes all numbers in the following format:
In order to send price of 130 AUD and volume of 0.1 ETH you will need to specify
130 * 100000000=**13000000000** 
and 0.1 * 100000000=**10000000** when making API calls.

This is same as Satoshi for BTC and precision of Wei  is not recognized at this stage.  

Thanks.
 
Regards,
Martin
