### ISSUE TITLE
What are the causes of 'Price is outside of market range'?

### ISSUE THREAD

**Issue by robmcd** [BTCMarkets/API#37]
I'm seeing this error 'Price is outside of market range' for the following order creation data:
{"currency":"AUD","instrument":"ETH","price":32115000000,"volume":3087568,"orderSide":"Bid","ordertype":"Limit","clientRequestId":"x"}

**Comment by nikolaisid** [comment]
I am getting the same error in response to this request:
{"currency":"AUD",
"instrument":"XRP",
"price":1000000,
"volume":100000000,
"orderSide":"Ask",
"ordertype":"Limit",
"clientRequestId":""}

The response is:
{"success":false,
"errorCode":3,
"errorMessage":"Price is outside of market range",
"id":0,
"clientRequestId":""}

Unless I am mistaken, the price in the request is equivalent to 0.01 AUD, which should be a valid price for this instrument.

EDIT: Just realised that I was trying to submit an Ask (sell) limit order for 0.01 AUD. Problem went away once I corrected the order type.

**Comment by martin-nginio** [comment]
Hi @robmcd 

This rule was originally put in place in order to prevent situations where a single API user would place orders that could potentially change the price outside of existing bid/sell orders. The issue was more apparent for new markets where orderbook was thin hence our team decided to place a restriction on order price to make sure they are within the existing market range (meaning price of an incoming new bid order is not significantly higher than existing ask orders in the orderbook and vice versa).   

I understand that those error codes only returned rarely and not very often, however I will forward this to our team for further review of the rule and see if such rules can be updated or removed moving forward. 

Thanks. 

Regards,
Martin

**Comment by longzheng** [comment]
@martin-nginio Hi martin, it would be great to clarify exactly what is the specific % of margin here?
