### ISSUE TITLE
non related historical data for a given instrument

### ISSUE THREAD

**Issue by StuAngel** [BTCMarkets/API#46]
Hi guys, Is it possible to query historical data using the API that is not directly related to an account, in short, all transaction data/log for a given instrument over period of time? eg. I wish to build my own historical graphs - Stu

**Comment by martin-nginio** [comment]
Hi @StuAngel 

You can use the following public API in order to retrieve historical trades for a given market (BTC/AUD in this case):
https://api.btcmarkets.net/market/BTC/AUD/trades?since=748105000
 
In above url, the `since` variable refers to a trade id that you received via previous API call. This should  help with pagination.   

(the same API is used by other third party websites for collecting historical data)

Thanks. 

Regards,
Martin

**Comment by StuAngel** [comment]
Hi Martin,

thanks for the quick response, I dont know why I was under the impression it represented transactions directly related to the account, but after having a quick play, I can assume the following,

no matter what I supply, it will only return transactions as long as they fall within 0:00 to now,
eg.

https://api.btcmarkets.net/market/BTC/AUD/trades?since=0
https://api.btcmarkets.net/market/BTC/AUD/trades?since=700000000

both start @ 2017:10:03 00:25:51 (1506950751)

I dont suppose there is any ?from=epoch&to=epoch in the pipeline? or even just go back further than 0:00 on the given day?

best regards

Stu

**Comment by martin-nginio** [comment]
I looked at the results and you are right about `since` variable not changing the results so thanks for pointing this out. 

I can confirm that since only refers to trade ids and not timestamps so the current API only returns recent trades.

Let me check and I will get back to you. I'm aware that our team is in the process of improving pagination for all APIs and I will add this also for review.

I'm not sure if the following temporary workaround could work for you: 
you can download the full historical data from a few websites including the following (look for btcmarketsAUD.csv.gz) although this one covers data only until July 2017:
http://api.bitcoincharts.com/v1/csv/ 

If you start calling the API it will always return the latest and hence you can collect the history. 

Thanks.

**Comment by StuAngel** [comment]
Hi Martin,

thanks for the feedback, I had a look over a couple of the csv files but I assume they are only movements specifically for BTC (epoch|price|amount), I will wait for your team to get done with their work, I dont suppose you any idea on how far away this might be? - if I could add something to a wish list? it would be the ability to be able to select an epoch range, eg - from=&to= (would allow zoom/ranged graphs without having to request huge amounts of data)

best regards

Stu

**Comment by martin-nginio** [comment]
Hi @StuAngel 

This has been raised as a priority with our development team. The pagination will still be based on trade is, however you will be able to move forward or backward in order to fetch new or old trades approperiately.  

Below is sample pagination that has recently been added to fund transfer history API allowing users to navigate new or old records.
https://github.com/BTCMarkets/API/wiki/Fund-Transfer-API#pagination 

I can't provide a definite date but my understanding is that the API will be ready within couple of weeks if not sooner. 

Thanks. 

Regards,
Martin

**Comment by StuAngel** [comment]
Hi Martin,

thanks for the info and I look forward to the changes,,

I agree the -> "cursor which is a useful method for retrieving data that changes in real time" will be useful, but not so much if I wanted to query what happened last thursday between midday and 1pm - but I can just query everything from 0 and store it in an external database so I can do those types of custom queries myself,

appreciate your time,

best regards

Stu

**Comment by martin-nginio** [comment]
thanks for your feedback. 

At this stage our team is unable to provide pagination based on timestamps and hence the assumption is that such analysis is done after collecting data via API and then using more appropriate systems (e.g. databases) for querying, aggregating, etc. 

Regards,
Martin

**Comment by 1rover1** [comment]
+1

I'd be keen to know when this has been implemented

**Comment by StuAngel** [comment]
Hi Martin, 

any thoughts on when "since=" might support older than the past 24 hours? as I know over a month ago you mentioned "This has been raised as a priority with our development team"

best regards

Stu

**Comment by martin-nginio** [comment]
Hi @StuAngel ,

Whilst a full upgrade to our API is not available yet, however for this particular API in question, you  should be able to use a new version that is already available:
/v2/market/BTC/AUD/trades

This new version solves the "since" issue (hence you can pass any trade: e.g. ?since=841094184 ) and it also introduces attributes in the API response in order to help with pagination and ability to retrieve full trade history. Please note that the response format is slightly different (mainly attribute names)

Our team will be documenting this gradually.

If you come across any issues please let us know. 

Thanks.  

Regards,
Martin

**Comment by cinooo** [comment]
Hi @martin-nginio is there any way to query for price by a particular date?

**Comment by chidg** [comment]
Hi @martin-nginio, this issue is still open over six months later. This would be a VERY useful feature considering the increased tax compliance burden Australians now have to deal with. We need to be able to query the historical price for a currency by date to calculate 'capital gains' for all trades.

**Comment by welldrake** [comment]
See potential solution here: https://github.com/BTCMarkets/API/issues/79#issuecomment-400892668

**Comment by justin-ngin** [comment]
Hi @StuAngel, @cinooo, @chidg 

We've just released a new endpoint that gives access to our entire history of tick/candles data in minute, hour, and day resolution. Check out the docs [here!](https://github.com/BTCMarkets/API/wiki/Market-data-API#historical-ticks)

Cheers,
Justin

**Comment by StuAngel** [comment]
hey Awesome @justin-ngin - thanks for the info and exactly 1 year to the day since the initial post ;)
