### ISSUE TITLE
No interface to obtain price history.

### ISSUE THREAD

**Issue by t-student** [BTCMarkets/API#79]
Based on the existing API I see no way to obtain complete price history. Is there an interface that supports such a request. If so, please can you provide an example. If not, then please can you provide such an interface?

**Comment by meeeee12** [comment]
What do you mean by price history? You can grab the market trade history and use that to see how much people were paying at a given time.

**Comment by t-student** [comment]
I may be wrong but the market trade history is limited to 500 records. I would like to be able to retrieve a price series with open, high, low, close (per hour or day if that is all that can be supported) for the full duration of the series.

**Comment by meeeee12** [comment]
Yes you are correct, it is limited to 500 at a time. That's why I have a server periodically grabbing the data so I can go further back that that. Apparently they are working on a v2 API which will not have that limit, it may also have those grouping features you want, for now you will have to implement it yourself.

**Comment by adamwilko** [comment]
Orderbook history would also be very useful for visualisation and AI training... 
meeeee12, has your server been grabbing that as well?

**Comment by ghost** [comment]
what you're after are the candles? other markets I'm using have a getCandles request. it returns up to 500 records of candles a whatever interval you pass in (min/hour/day etc).
{open,close,max,min,datetime}

would be great if that was supported here

**Comment by shazbert** [comment]
@meeeee12 
When using Using GET https://api.btcmarkets.net/market/LTC/AUD/trades?since=0 
Results most recent data for example. 

I was just wondering how you iterated to past data because since relates to tradeID and not timestamp and since meaning everything from that timestamp onward. 

Does anybody know the trade ID's for the start of the historic data per currency pair?

**Comment by welldrake** [comment]
It's not via the api itself, but this works for now:
[`https://www.btcmarkets.net/data/market/BTCMarkets/BTC/AUD/tickByTime?timeWindow=day&since=1299974400000`](https://www.btcmarkets.net/data/market/BTCMarkets/BTC/AUD/tickByTime?timeWindow=day&since=1299974400000)

You can change the following parameters:
- **BTC** - quote currency, currently `BTC, LTC, ETH, ETC, BCH, XRP`
- **AUD** - base currency, currently `AUD, BTC`
- **timeWindow** - currently `minute, hour, day`
- **since** - unix time in milliseconds, earliest is currently 1299974400000 or 13 March 2011 00:00:00 GMT

There's an alternative form using **from** and **to** instead of **since**, but only seems to work at the **day** level:
[`https://www.btcmarkets.net/data/market/BTCMarkets/BTC/AUD/tickByTime/day?from=1299974400000&to=1559174399999`](https://www.btcmarkets.net/data/market/BTCMarkets/BTC/AUD/tickByTime/day?from=1299974400000&to=1559174399999)

The response is a json in the form below:
```json
{
	"error": null,
	"result": "success",
	"errorCode": null,
	"marketId": 2001,
	"agency": "BTCMarkets",
	"currency": "AUD",
	"ticks": [
		[1529971200000, 841500000000, 847367000000, 815169000000, 817106000000, 17456113672],
		[1530057600000, 819569000000, 838967000000, 812040000000, 835478000000, 22094774935],
		[1530144000000, 835478000000, 840999000000, 829668000000, 830501000000, 2576462657]
	]
}
```

Each tick gives the following where time is in milliseconds and prices and volumes are in satoshis:
```
[timestamp, open, high, low, close, volume]
```

If you get the parameters wrong or the timestamps are out of limits, you'll get:
```json
{
	"error": "generic error.",
	"result": "fail",
	"errorCode": null,
	"marketId": 0,
	"agency": null,
	"currency": null,
	"ticks": []
}
```

@justin-ngin - perhaps you can get this endpoint added to the proper api please?

**Comment by shazbert** [comment]
@welldrake Thank you very much for the explanation!

**Comment by squeaky-nose** [comment]
Can we please make tickbytime a officially publicly supported API? I am unable to access it after cloud flair was introduced with DDOS protection.

**Comment by justin-ngin** [comment]
Hi all,

Absolutely, I'm advocating for this functionality to be added to the V2 api, with pagination. The data format will probably be slightly different, but the information will be the same.

Cheers,
Justin

**Comment by squeaky-nose** [comment]
Thanks Justin -- sooner the better! Is there somewhere we can keep track of new API endpoints as they are added?

**Comment by justin-ngin** [comment]
Hi @sushant40 ,

That's a great question. We can send promotional emails with announcements for new API features, but I'm curious what other methods you guys might have in mind.

Best,
Justin

**Comment by welldrake** [comment]
A great way would be to have a list of endpoints, with the version, date first made available, date last modified

**Comment by squeaky-nose** [comment]
Any update on this?

**Comment by justin-ngin** [comment]
Hi @sushant40, @shazbert, @welldrake, @t-student, @meeeee12, @adamwilko, @jdceds 

We have recently released this [endpoint](https://github.com/BTCMarkets/API/wiki/Market-data-API#historical-ticks) to v2! 

Cheers,
Justin

**Comment by squeaky-nose** [comment]
Thanks @justin-ngin.... Will try hitting it this weekend!
